#ifndef QUPARTICLEACCEL_GLOBAL_H
#define QUPARTICLEACCEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QUPARTICLEACCEL_LIBRARY)
#  define QUPARTICLEACCEL_EXPORT Q_DECL_EXPORT
#else
#  define QUPARTICLEACCEL_EXPORT Q_DECL_IMPORT
#endif

#endif // QUPARTICLEACCEL_GLOBAL_H
